services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=alquilerscooters'
      - 'POSTGRES_PASSWORD=24112005'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'  # Asegúrate de que el puerto está correctamente mapeado

  app:
    image: openjdk:17-jdk-slim  # o tu imagen específica si la tienes
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/alquilerscooters'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=24112005'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
